<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Test\Unit\Model\ResourceModel;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\DB\Adapter\AdapterInterface;
use Magento\Framework\DB\Select;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use ReadyData\Import\Model\ResourceModel\UrlRewrite;

class UrlRewriteTest extends TestCase
{
    private const TABLE = 'url_rewrite';
    private const RELATION_TABLE = 'catalog_url_rewrite_product_category';

    private AdapterInterface&MockObject $connection;
    private ResourceConnection&MockObject $resourceConnection;
    private ScopeConfigInterface&MockObject $scopeConfig;
    private UrlRewrite $resource;

    /**
     * Ordered log of the write calls, so a test can assert that the delete
     * happens before the insert rather than merely that both happened.
     *
     * @var array<int, array{method: string, table: string, args: array}>
     */
    private array $calls = [];

    protected function setUp(): void
    {
        $this->connection = $this->createMock(AdapterInterface::class);
        $this->resourceConnection = $this->createMock(ResourceConnection::class);
        $this->resourceConnection->method('getConnection')->willReturn($this->connection);
        // getTableName is identity in these tests (no table prefix).
        $this->resourceConnection->method('getTableName')->willReturnArgument(0);
        $this->connection->method('select')->willReturnCallback(fn (): Select => $this->passthroughSelect());

        $this->connection->method('delete')->willReturnCallback(
            function (string $table, $condition): int {
                $this->calls[] = ['method' => 'delete', 'table' => $table, 'args' => [$condition]];

                return 0;
            }
        );
        $this->connection->method('insertOnDuplicate')->willReturnCallback(
            function (string $table, array $rows, array $columns): int {
                $this->calls[] = [
                    'method' => 'insertOnDuplicate',
                    'table' => $table,
                    'args' => ['rows' => $rows, 'columns' => $columns],
                ];

                return count($rows);
            }
        );

        $this->scopeConfig = $this->createMock(ScopeConfigInterface::class);

        $this->resource = new UrlRewrite($this->resourceConnection, $this->scopeConfig);
    }

    /**
     * The row this statement writes must come out wholly owned by the writer.
     *
     * url_rewrite is unique on (request_path, store_id) and this insert writes
     * THROUGH that key, so the duplicate branch is reachable — by a concurrent
     * claim, but also deterministically within one batch (see
     * testANotVisibleSiblingsRowIsTakenOverRatherThanCrossWired). Overwriting
     * only target_path leaves a row that claims one product and resolves to
     * another: the storefront serves the wrong product, deleteAutogenerated()
     * matches on the stale entity_id, and saveProductCategoryRelations() files
     * the relation under the wrong product.
     */
    public function testReplaceOverwritesEveryColumnThatSaysWhoOwnsTheRow(): void
    {
        $this->resource->replaceProductRewrites([42], [1], [$this->row(42, 'shirt.html', 1)]);

        $insert = $this->lastCall('insertOnDuplicate');
        self::assertNotNull($insert);
        self::assertContains('entity_id', $insert['args']['columns']);
        self::assertContains('entity_type', $insert['args']['columns']);
    }

    /**
     * Everything the row points at has to move with its ownership, or a
     * taken-over row keeps the previous owner's redirect semantics.
     */
    public function testReplaceAlsoOverwritesWhatTheRowPointsAt(): void
    {
        $this->resource->replaceProductRewrites([42], [1], [$this->row(42, 'shirt.html', 1)]);

        $insert = $this->lastCall('insertOnDuplicate');
        self::assertNotNull($insert);
        foreach (['target_path', 'redirect_type', 'is_autogenerated', 'metadata'] as $column) {
            self::assertContains($column, $insert['args']['columns']);
        }
    }

    /**
     * Our own live rows go first, so the insert re-creates them cleanly. The
     * delete deliberately spares redirect_type != 0: those are the 301 history
     * rows a slug change left behind, and losing them would break every old URL.
     */
    public function testReplaceDeletesOurLiveAutogeneratedRowsBeforeInserting(): void
    {
        $this->resource->replaceProductRewrites([42], [1], [$this->row(42, 'shirt.html', 1)]);

        self::assertSame(
            ['delete', 'insertOnDuplicate'],
            array_column($this->calls, 'method')
        );

        $condition = $this->calls[0]['args'][0];
        self::assertSame(1, $condition['is_autogenerated = ?']);
        self::assertSame(0, $condition['redirect_type = ?']);
        self::assertSame(UrlRewrite::ENTITY_TYPE_PRODUCT, $condition['entity_type = ?']);
        self::assertSame([42], $condition['entity_id IN (?)']);
        self::assertSame([1], $condition['store_id IN (?)']);
    }

    /**
     * The scenario that needs no concurrency at all. Product 99 goes not-visible
     * in store 1, so it is NOT in $entityIds and its live row survives the
     * delete; product 42 in the same batch adopts its slug. The row must end up
     * owned by 42 — otherwise the caller's not-visible cleanup, which deletes by
     * entity_id, removes the URL 42 just gained.
     */
    public function testANotVisibleSiblingsRowIsTakenOverRatherThanCrossWired(): void
    {
        $this->resource->replaceProductRewrites([42], [1], [$this->row(42, 'shirt.html', 1)]);

        $insert = $this->lastCall('insertOnDuplicate');
        self::assertNotNull($insert);
        // The delete cannot have removed 99's row...
        self::assertSame([42], $this->calls[0]['args'][0]['entity_id IN (?)']);
        // ...so entity_id has to be in the overwrite set for 42 to end up owning it.
        self::assertContains('entity_id', $insert['args']['columns']);
        self::assertSame(42, $insert['args']['rows'][0]['entity_id']);
    }

    public function testReplaceIsANoOpWithoutEntitiesOrStores(): void
    {
        $this->resource->replaceProductRewrites([], [1], [$this->row(42, 'shirt.html', 1)]);
        $this->resource->replaceProductRewrites([42], [], [$this->row(42, 'shirt.html', 1)]);

        self::assertSame([], $this->calls);
    }

    /**
     * Chunking is what keeps a large batch under max_allowed_packet.
     */
    public function testRowsAreChunked(): void
    {
        $rows = [];
        for ($i = 0; $i < 1001; $i++) {
            $rows[] = $this->row(1000 + $i, "p{$i}.html", 1);
        }

        $this->resource->replaceProductRewrites([1000], [1], $rows);

        $inserts = array_values(array_filter(
            $this->calls,
            static fn (array $c): bool => $c['method'] === 'insertOnDuplicate'
        ));
        self::assertCount(2, $inserts);
        self::assertCount(1000, $inserts[0]['args']['rows']);
        self::assertCount(1, $inserts[1]['args']['rows']);
    }

    /**
     * This is the consumer that turns a cross-wired rewrite into a cross-wired
     * category relation: the product_id comes from the ROW's entity_id, not from
     * anything the caller passed. It is why entity_id has to be right.
     */
    public function testSaveProductCategoryRelationsFilesTheRelationUnderTheRowsEntityId(): void
    {
        $this->connection->method('fetchAll')->willReturn([
            ['url_rewrite_id' => 500, 'entity_id' => 7, 'metadata' => '{"category_id":"5"}'],
        ]);

        $this->resource->saveProductCategoryRelations([7], [1]);

        $insert = $this->lastCall('insertOnDuplicate');
        self::assertNotNull($insert);
        self::assertSame(self::RELATION_TABLE, $insert['table']);
        self::assertSame(
            [['url_rewrite_id' => 500, 'category_id' => 5, 'product_id' => 7]],
            $insert['args']['rows']
        );
    }

    public function testSaveProductCategoryRelationsSkipsRowsWithoutACategoryId(): void
    {
        $this->connection->method('fetchAll')->willReturn([
            ['url_rewrite_id' => 500, 'entity_id' => 7, 'metadata' => null],
            ['url_rewrite_id' => 501, 'entity_id' => 7, 'metadata' => 'not json'],
        ]);

        $this->resource->saveProductCategoryRelations([7], [1]);

        self::assertSame([], $this->calls);
    }

    /**
     * Excluding our own products is what lets a re-import keep its own paths —
     * and is also what makes a batch sibling's surviving row reachable by the
     * insert's duplicate branch.
     */
    public function testFindConflictsKeysTakenPathsByStore(): void
    {
        $this->connection->method('fetchAll')->willReturn([
            ['store_id' => '1', 'request_path' => 'shirt.html'],
            ['store_id' => '2', 'request_path' => 'shirt.html'],
        ]);

        $conflicts = $this->resource->findConflicts(['shirt.html'], [42]);

        self::assertSame([1 => ['shirt.html' => true], 2 => ['shirt.html' => true]], $conflicts);
    }

    public function testFindConflictsIsANoOpWithoutPaths(): void
    {
        $this->connection->expects(self::never())->method('fetchAll');

        self::assertSame([], $this->resource->findConflicts([], [42]));
    }

    /**
     * @return array<string, mixed>
     */
    private function row(int $entityId, string $requestPath, int $storeId): array
    {
        return [
            'entity_type' => UrlRewrite::ENTITY_TYPE_PRODUCT,
            'entity_id' => $entityId,
            'request_path' => $requestPath,
            'target_path' => 'catalog/product/view/id/' . $entityId,
            'redirect_type' => 0,
            'store_id' => $storeId,
            'is_autogenerated' => 1,
            'metadata' => null,
        ];
    }

    /**
     * @return array{method: string, table: string, args: array}|null
     */
    private function lastCall(string $method): ?array
    {
        $matching = array_values(array_filter(
            $this->calls,
            static fn (array $c): bool => $c['method'] === $method
        ));

        return $matching ? $matching[count($matching) - 1] : null;
    }

    private function passthroughSelect(): Select&MockObject
    {
        $select = $this->createMock(Select::class);
        foreach (['from', 'join', 'joinLeft', 'columns', 'where', 'order', 'limit'] as $method) {
            $select->method($method)->willReturnSelf();
        }

        return $select;
    }
}
