<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Model\Processor;

use ReadyData\Import\Api\Data\ProductInterface;
use ReadyData\Import\Model\BatchContext;
use ReadyData\Import\Model\Cache\AttributeMetadataCache;
use ReadyData\Import\Model\Cache\StoreWebsiteMap;
use ReadyData\Import\Model\Config;
use ReadyData\Import\Model\Processor\UrlRewrite\CategoryPathRewriteBuilder;
use ReadyData\Import\Model\ResourceModel\CategoryLink;
use ReadyData\Import\Model\ResourceModel\EavValue;
use ReadyData\Import\Model\ResourceModel\UrlRewrite;

/**
 * Regenerates product URL rewrites for every store of the product's websites,
 * mirroring the native catalog-url-rewrite output:
 *  - the canonical (direct) product rewrite;
 *  - category-path rewrites incl. anchor-ancestor rollup, when the store has
 *    catalog/seo/generate_category_product_rewrites enabled;
 *  - 301 redirects from changed request paths, when the store has
 *    catalog/seo/save_rewrites_history enabled;
 *  - visibility-aware: not-visible products get no rewrites and their existing
 *    autogenerated rewrites are removed.
 *
 * Runs after CategoryLinkProcessor (sort order 750 > 700) so the final
 * product↔category assignments are readable.
 */
class UrlRewriteProcessor implements ProcessorInterface
{
    private const VISIBILITY_NOT_VISIBLE = 1;
    private const REDIRECT_PERMANENT = 301;
    private const CANONICAL_KEY = 'c';

    public function __construct(
        private readonly UrlRewrite $urlRewriteResource,
        private readonly EavValue $eavValue,
        private readonly AttributeMetadataCache $attributeMetadataCache,
        private readonly StoreWebsiteMap $storeWebsiteMap,
        private readonly Config $config,
        private readonly CategoryLink $categoryLink,
        private readonly CategoryPathRewriteBuilder $categoryPathRewriteBuilder
    ) {
    }

    public function process(BatchContext $context): void
    {
        $urlKeys = $this->resolveUrlKeys($context);
        $websiteIdsBySku = $context->get(WebsiteProcessor::CONTEXT_WEBSITE_IDS, []);
        $linkIds = $context->get(EntityProcessor::CONTEXT_LINK_IDS, []);
        $strategy = $this->config->getUrlRewriteConflictStrategy();

        // sku => [store ids] for products with a url_key and a resolved entity.
        // The DEFAULT-scope key is what decides whether a product has one at
        // all: a store override with nothing to override is not a slug.
        $storeIdsBySku = [];
        $skuByEntity = [];
        foreach (array_keys($context->getValidProducts()) as $sku) {
            $entityId = $context->getEntityId($sku);
            if (($urlKeys[$sku][0] ?? '') === '' || $entityId === null) {
                continue;
            }
            $storeIdsBySku[$sku] = $this->storeWebsiteMap->getStoreIdsForWebsites($websiteIdsBySku[$sku] ?? []);
            $skuByEntity[$entityId] = (string)$sku;
        }
        if (!$storeIdsBySku) {
            return;
        }

        $allStoreIds = array_values(array_unique(array_merge(...array_values($storeIdsBySku))));
        // Only knowable once the stores are: a store override this batch did
        // not write is still the slug that store's rewrite must be built from.
        $urlKeys = $this->backfillScopedUrlKeys($context, $urlKeys, $allStoreIds);
        $visibility = $this->loadVisibility(array_values($linkIds), $allStoreIds);

        // Canonical candidates + per-store visible-entity sets + not-visible sets.
        $canonical = [];
        $visibleEntitiesByStore = [];
        $notVisibleByStore = [];
        foreach ($storeIdsBySku as $sku => $storeIds) {
            $entityId = $context->getEntityId((string)$sku);
            $linkId = $linkIds[$sku] ?? null;
            foreach ($storeIds as $storeId) {
                if ($linkId !== null
                    && (int)($visibility[$storeId][$linkId] ?? 0) === self::VISIBILITY_NOT_VISIBLE
                ) {
                    $notVisibleByStore[$storeId][$entityId] = true;
                    continue;
                }
                $visibleEntitiesByStore[$storeId][$entityId] = true;
                $canonical[] = [
                    'sku' => (string)$sku,
                    'entity_id' => $entityId,
                    'store_id' => $storeId,
                    'request_path' => self::urlKeyFor($urlKeys, (string)$sku, $storeId)
                        . $this->urlRewriteResource->getProductUrlSuffix($storeId),
                    'target_path' => 'catalog/product/view/id/' . $entityId,
                    'metadata' => null,
                    'category_key' => self::CANONICAL_KEY,
                ];
            }
        }

        $category = $this->buildCategoryCandidates($context, $skuByEntity, $urlKeys, $visibleEntitiesByStore);

        // Resolve conflicts (canonical first so it keeps the clean path), build rows.
        $allPaths = array_values(array_unique(array_map(
            static fn (array $c): string => $c['request_path'],
            array_merge($canonical, $category)
        )));
        $conflicts = $allPaths
            ? $this->urlRewriteResource->findConflicts($allPaths, $context->getValidEntityIds())
            : [];

        $rows = [];
        $touchedEntityIds = [];
        $touchedStoreIds = [];
        $claimed = [];
        $finalByKey = [];
        $hasCategoryRows = false;
        foreach (array_merge($canonical, $category) as $candidate) {
            $sku = $candidate['sku'];
            // A SKU failed during conflict resolution (error strategy) must not
            // still receive its remaining (e.g. category-path) rewrites.
            if ($context->isFailed($sku)) {
                continue;
            }
            $storeId = $candidate['store_id'];
            $requestPath = $candidate['request_path'];
            if (isset($conflicts[$storeId][$requestPath]) || isset($claimed[$storeId][$requestPath])) {
                $requestPath = $this->resolveConflict($context, $sku, $storeId, $requestPath, $strategy);
                if ($requestPath === null) {
                    continue;
                }
            }
            $claimed[$storeId][$requestPath] = true;
            $rows[] = [
                'entity_type' => UrlRewrite::ENTITY_TYPE_PRODUCT,
                'entity_id' => $candidate['entity_id'],
                'request_path' => $requestPath,
                'target_path' => $candidate['target_path'],
                'redirect_type' => 0,
                'store_id' => $storeId,
                'is_autogenerated' => 1,
                'metadata' => $candidate['metadata'],
            ];
            $hasCategoryRows = $hasCategoryRows || $candidate['metadata'] !== null;
            $touchedEntityIds[$candidate['entity_id']] = true;
            $touchedStoreIds[$storeId] = true;
            $finalByKey[$candidate['entity_id']][$storeId][$candidate['category_key']] = $requestPath;
        }

        if ($rows) {
            $rows = array_merge(
                $rows,
                $this->buildRedirects(
                    array_keys($touchedEntityIds),
                    array_keys($touchedStoreIds),
                    $finalByKey,
                    $claimed
                )
            );
            $this->urlRewriteResource->replaceProductRewrites(
                array_keys($touchedEntityIds),
                array_keys($touchedStoreIds),
                $rows
            );
            if ($hasCategoryRows) {
                $this->urlRewriteResource->saveProductCategoryRelations(
                    array_keys($touchedEntityIds),
                    array_keys($touchedStoreIds)
                );
            }
        }

        // Drop rewrites of products that became not-visible (per store, precise).
        foreach ($notVisibleByStore as $storeId => $entitySet) {
            $this->urlRewriteResource->deleteAutogenerated(array_keys($entitySet), [$storeId]);
        }
    }

    /**
     * Category-path + anchor candidates per enabled store, for visible products
     * only. Uses the final assignments written by CategoryLinkProcessor.
     *
     * @param array<int, string> $skuByEntity
     * @param array<string, array<int, string>> $urlKeys sku => store_id => url_key
     * @param array<int, array<int, true>> $visibleEntitiesByStore store => entity set
     * @return array<int, array<string, mixed>> flat candidate list
     */
    private function buildCategoryCandidates(
        BatchContext $context,
        array $skuByEntity,
        array $urlKeys,
        array $visibleEntitiesByStore
    ): array {
        $enabledStores = array_filter(
            array_keys($visibleEntitiesByStore),
            fn (int $storeId): bool => $this->urlRewriteResource->isCategoryRewritesEnabled($storeId)
        );
        if (!$enabledStores) {
            return [];
        }

        $assignments = $this->categoryLink->getAssignments($context->getValidEntityIds());
        if (!$assignments) {
            return [];
        }

        $candidates = [];
        foreach ($enabledStores as $storeId) {
            $visibleAssignments = array_intersect_key($assignments, $visibleEntitiesByStore[$storeId]);
            if (!$visibleAssignments) {
                continue;
            }
            // Rebuilt per store: the slug a category path is suffixed with is
            // the one that store view resolves on, not the default one.
            $urlKeyByEntity = [];
            foreach ($skuByEntity as $entityId => $sku) {
                $urlKey = self::urlKeyFor($urlKeys, $sku, $storeId);
                if ($urlKey !== '') {
                    $urlKeyByEntity[$entityId] = $urlKey;
                }
            }
            $built = $this->categoryPathRewriteBuilder->build(
                $visibleAssignments,
                $urlKeyByEntity,
                $storeId,
                $this->urlRewriteResource->getProductUrlSuffix($storeId)
            );
            foreach ($built as $entityId => $entityCandidates) {
                foreach ($entityCandidates as $candidate) {
                    $candidates[] = [
                        'sku' => $skuByEntity[$entityId] ?? '',
                        'entity_id' => $entityId,
                        'store_id' => $storeId,
                        'request_path' => $candidate['request_path'],
                        'target_path' => $candidate['target_path'],
                        'metadata' => json_encode(['category_id' => (string)$candidate['category_id']]),
                        'category_key' => $candidate['category_id'],
                    ];
                }
            }
        }

        return $candidates;
    }

    /**
     * 301 rows for request paths that changed: for each existing autogenerated
     * rewrite whose category context still resolves to a (different) new path.
     *
     * @param int[] $entityIds
     * @param int[] $storeIds
     * @param array<int, array<int, array<int|string, string>>> $finalByKey
     *        entity_id => store_id => category_key => new request path
     * @param array<int, array<string, true>> $claimed store_id => set of request paths
     *        written this batch as live rewrites
     * @return array<int, array<string, mixed>>
     */
    private function buildRedirects(array $entityIds, array $storeIds, array $finalByKey, array $claimed): array
    {
        $historyStores = array_values(array_filter(
            $storeIds,
            fn (int $storeId): bool => $this->urlRewriteResource->isSaveRewritesHistory($storeId)
        ));
        if (!$historyStores) {
            return [];
        }

        $redirects = [];
        foreach ($this->urlRewriteResource->getExistingAutogenerated($entityIds, $historyStores) as $old) {
            $key = $this->categoryKeyFromMetadata($old['metadata']);
            $newPath = $finalByKey[$old['entity_id']][$old['store_id']][$key] ?? null;
            if ($newPath === null || $newPath === $old['request_path']) {
                continue;
            }
            // The old path was re-claimed as a live rewrite this batch (e.g.
            // another product adopted the freed url_key) — do not shadow it
            // with a 301, which would overwrite that product's rewrite.
            if (isset($claimed[$old['store_id']][$old['request_path']])) {
                continue;
            }
            $redirects[] = [
                'entity_type' => UrlRewrite::ENTITY_TYPE_PRODUCT,
                'entity_id' => $old['entity_id'],
                'request_path' => $old['request_path'],
                'target_path' => $newPath,
                'redirect_type' => self::REDIRECT_PERMANENT,
                'store_id' => $old['store_id'],
                'is_autogenerated' => 0,
                'metadata' => $old['metadata'],
            ];
        }

        return $redirects;
    }

    /**
     * @return int|string the category id, or CANONICAL_KEY for non-category rows
     */
    private function categoryKeyFromMetadata(?string $metadata): int|string
    {
        if ($metadata === null || $metadata === '') {
            return self::CANONICAL_KEY;
        }
        $decoded = json_decode($metadata, true);

        return is_array($decoded) && isset($decoded['category_id'])
            ? (int)$decoded['category_id']
            : self::CANONICAL_KEY;
    }

    /**
     * Visibility per store keyed by link id, with store-0 fallback.
     *
     * @param int[] $linkIds
     * @param int[] $storeIds
     * @return array<int, array<int, int>> store_id => [link_id => visibility]
     */
    private function loadVisibility(array $linkIds, array $storeIds): array
    {
        if (!$linkIds) {
            return [];
        }
        $meta = $this->attributeMetadataCache->get(ProductInterface::VISIBILITY);
        if ($meta === null) {
            return [];
        }
        $attributeId = $meta['attribute_id'];
        $backendType = $meta['backend_type'];
        $store0 = $this->eavValue->getValues($backendType, $attributeId, $linkIds, 0);

        $result = [];
        foreach ($storeIds as $storeId) {
            $storeValues = $storeId === 0
                ? $store0
                : $this->eavValue->getValues($backendType, $attributeId, $linkIds, $storeId);
            // Store-specific values override the store-0 defaults.
            $result[$storeId] = array_map('intval', $storeValues + $store0);
        }

        return $result;
    }

    /**
     * The slug a store view resolves this product on: its own override when it
     * has one, the default-scope key otherwise — exactly how Magento reads a
     * store-scoped EAV value.
     *
     * @param array<string, array<int, string>> $urlKeys sku => store_id => url_key
     */
    private static function urlKeyFor(array $urlKeys, string $sku, int $storeId): string
    {
        $scoped = $urlKeys[$sku][$storeId] ?? '';

        return $scoped !== '' ? $scoped : ($urlKeys[$sku][0] ?? '');
    }

    /**
     * Default-scope url_keys written this batch (from EavValueProcessor),
     * backfilled with the stored one for existing products the payload didn't
     * touch.
     *
     * @return array<string, array<int, string>> sku => store_id => url_key
     */
    private function resolveUrlKeys(BatchContext $context): array
    {
        $urlKeys = $context->get(EavValueProcessor::CONTEXT_URL_KEYS, []);
        $linkIds = $context->get(EntityProcessor::CONTEXT_LINK_IDS, []);

        $missingLinkIds = [];
        foreach ($context->getValidProducts() as $sku => $product) {
            if (!isset($urlKeys[$sku][0]) && isset($linkIds[$sku])) {
                $missingLinkIds[$linkIds[$sku]] = $sku;
            }
        }
        if ($missingLinkIds) {
            $meta = $this->attributeMetadataCache->get(ProductInterface::URL_KEY);
            if ($meta !== null) {
                $stored = $this->eavValue->getValues(
                    $meta['backend_type'],
                    $meta['attribute_id'],
                    array_keys($missingLinkIds)
                );
                foreach ($stored as $linkId => $urlKey) {
                    $urlKeys[$missingLinkIds[(int)$linkId]][0] = (string)$urlKey;
                }
            }
        }

        return $urlKeys;
    }

    /**
     * Fill in the STORE-scoped url_keys already in the database for the (sku,
     * store) pairs this batch did not write.
     *
     * Without it a payload that sets only the default key would regenerate
     * every store's rewrite from that key, silently discarding a store
     * override — including one this module wrote on an earlier run, which would
     * make a replay flip the storefront URL back and forth.
     *
     * @param array<string, array<int, string>> $urlKeys
     * @param int[] $storeIds
     * @return array<string, array<int, string>>
     */
    private function backfillScopedUrlKeys(BatchContext $context, array $urlKeys, array $storeIds): array
    {
        $linkIds = $context->get(EntityProcessor::CONTEXT_LINK_IDS, []);
        $meta = $this->attributeMetadataCache->get(ProductInterface::URL_KEY);
        $storeIds = array_values(array_filter($storeIds, static fn (int $storeId): bool => $storeId !== 0));
        if ($meta === null || !$storeIds || !$linkIds) {
            return $urlKeys;
        }

        $skuByLinkId = [];
        foreach ($context->getValidProducts() as $sku => $product) {
            if (isset($linkIds[$sku])) {
                $skuByLinkId[$linkIds[$sku]] = (string)$sku;
            }
        }
        if (!$skuByLinkId) {
            return $urlKeys;
        }

        // Every scope in one query — the same read MediaProcessor uses for its
        // store-scoped role attributes. Per-store reads would cost one query per
        // store view on a catalog where that number is the whole point.
        $wanted = array_fill_keys($storeIds, true);
        $stored = $this->eavValue->getValuesForStores(
            $meta['backend_type'],
            [$meta['attribute_id']],
            array_keys($skuByLinkId)
        );

        foreach ($stored as $linkId => $byAttribute) {
            $sku = $skuByLinkId[(int)$linkId] ?? null;
            if ($sku === null) {
                continue;
            }
            foreach ($byAttribute[$meta['attribute_id']] ?? [] as $storeId => $urlKey) {
                // Never over the batch's own write: that is the newer value.
                if (isset($wanted[$storeId]) && !isset($urlKeys[$sku][$storeId]) && (string)$urlKey !== '') {
                    $urlKeys[$sku][(int)$storeId] = (string)$urlKey;
                }
            }
        }

        return $urlKeys;
    }

    /**
     * @return string|null the request path to use, or null to skip this rewrite
     */
    private function resolveConflict(
        BatchContext $context,
        string $sku,
        int $storeId,
        string $requestPath,
        string $strategy
    ): ?string {
        switch ($strategy) {
            case Config::URL_CONFLICT_APPEND:
                $suffix = $this->urlRewriteResource->getProductUrlSuffix($storeId);
                $base = $suffix !== '' && str_ends_with($requestPath, $suffix)
                    ? substr($requestPath, 0, -strlen($suffix))
                    : $requestPath;
                $unique = $base . '-' . $context->getEntityId($sku) . $suffix;
                $context->addMessage($sku, sprintf(
                    'URL "%s" is taken in store %d; used "%s" instead.',
                    $requestPath,
                    $storeId,
                    $unique
                ));

                return $unique;
            case Config::URL_CONFLICT_ERROR:
                $context->fail($sku, sprintf('URL "%s" is already taken in store %d.', $requestPath, $storeId));

                return null;
            default:
                $context->addMessage($sku, sprintf(
                    'URL "%s" is taken in store %d; rewrite skipped.',
                    $requestPath,
                    $storeId
                ));

                return null;
        }
    }

    public function isEnabled(): bool
    {
        return true;
    }

    public function getSortOrder(): int
    {
        return 750;
    }
}
