<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Events\Console;

use Magento\Framework\Component\ComponentRegistrar;
use ReadyData\Events\Model\Catalogue;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Writes etc/events.xml from the catalogue.
 *
 * The generated file is committed, so a normal install needs no generation step
 * — that matters, because a module that silently emits nothing until someone
 * remembers to run a CLI command is a support case waiting to happen. This
 * command exists for the case the plan calls the analogue of Adobe's --force:
 * a code outside the shipped catalogue, which needs a regenerate and a
 * di:compile before it can be subscribed to.
 */
class GenerateHooksCommand extends Command
{
    public function __construct(
        private readonly Catalogue $catalogue,
        private readonly ComponentRegistrar $componentRegistrar,
        ?string $name = null
    ) {
        parent::__construct($name);
    }

    protected function configure(): void
    {
        $this->setName('readydata:events:generate')
            ->setDescription('Regenerate ReadyData_Events observer registrations from the curated catalogue')
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Print what would be written and change nothing');

        parent::configure();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $modulePath = $this->componentRegistrar->getPath(ComponentRegistrar::MODULE, 'ReadyData_Events');
        if ($modulePath === null) {
            $output->writeln('<error>ReadyData_Events is not registered.</error>');

            return Command::FAILURE;
        }

        $names = $this->catalogue->eventNames();
        $xml = $this->render($names);
        $target = $modulePath . '/etc/events.xml';

        if ($input->getOption('dry-run')) {
            $output->writeln(sprintf('<info>%d observer registrations</info> would be written to %s', count($names), $target));

            return Command::SUCCESS;
        }

        if (file_put_contents($target, $xml) === false) {
            $output->writeln(sprintf('<error>Could not write %s</error>', $target));

            return Command::FAILURE;
        }

        $output->writeln(sprintf('<info>Wrote %d observer registrations</info> to %s', count($names), $target));
        $output->writeln('Run <comment>bin/magento setup:di:compile</comment> on a compiled deployment for plugin changes to take effect.');

        return Command::SUCCESS;
    }

    /** @param string[] $names */
    private function render(array $names): string
    {
        $xml = "<?xml version=\"1.0\"?>\n"
            . "<!--\n"
            . "    GENERATED by `bin/magento readydata:events:generate` from\n"
            . "    ReadyData\\Events\\Model\\Catalogue. Do not hand-edit: edit the catalogue\n"
            . "    and regenerate, or the next run silently reverts the change.\n"
            . "\n"
            . "    Every registration points at one shared observer whose first action is an\n"
            . "    O(1) subscription lookup, so a hooked-but-unsubscribed event costs a hash\n"
            . "    lookup and returns.\n"
            . "-->\n"
            . "<config xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
            . "        xsi:noNamespaceSchemaLocation=\"urn:magento:framework:Event/etc/events.xsd\">\n";

        foreach ($names as $name) {
            $xml .= sprintf(
                "    <event name=\"%s\">\n"
                . "        <observer name=\"readydata_events_%s\" instance=\"%s\"/>\n"
                . "    </event>\n",
                $name,
                $name,
                'ReadyData\Events\Observer\CaptureObserver'
            );
        }

        return $xml . "</config>\n";
    }
}
