<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Test\Unit\Model\Processor;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use ReadyData\Import\Model\BatchContext;
use ReadyData\Import\Model\Cache\AttributeMetadataCache;
use ReadyData\Import\Model\Cache\StoreWebsiteMap;
use ReadyData\Import\Model\Config;
use ReadyData\Import\Model\Data\Product;
use ReadyData\Import\Model\Data\ProductStoreValues;
use ReadyData\Import\Model\Processor\EavValueProcessor;
use ReadyData\Import\Model\Processor\EntityProcessor;
use ReadyData\Import\Model\Processor\UrlRewrite\CategoryPathRewriteBuilder;
use ReadyData\Import\Model\Processor\UrlRewriteProcessor;
use ReadyData\Import\Model\Processor\WebsiteProcessor;
use ReadyData\Import\Model\ImportLocks;
use ReadyData\Import\Model\ResourceModel\CategoryLink;
use ReadyData\Import\Model\ResourceModel\EavValue;
use ReadyData\Import\Model\ResourceModel\ProductEntity;
use ReadyData\Import\Model\ResourceModel\UrlRewrite;

class UrlRewriteProcessorTest extends TestCase
{
    private UrlRewrite&MockObject $urlRewriteResource;
    private EavValue&MockObject $eavValue;
    private AttributeMetadataCache&MockObject $attributeMetadataCache;
    private StoreWebsiteMap&MockObject $storeWebsiteMap;
    private Config&MockObject $config;
    private CategoryLink&MockObject $categoryLink;
    private CategoryPathRewriteBuilder&MockObject $categoryPathRewriteBuilder;
    private ProductEntity&MockObject $productEntity;
    private UrlRewriteProcessor $processor;

    /**
     * @var array{entityIds: int[], storeIds: int[], rows: array<int, array>}|null
     */
    private ?array $replaced = null;

    /**
     * @var array{entityIds: int[], storeIds: int[]}|null
     */
    private ?array $deleted = null;

    protected function setUp(): void
    {
        $this->urlRewriteResource = $this->createMock(UrlRewrite::class);
        $this->urlRewriteResource->method('getProductUrlSuffix')->willReturn('.html');
        $this->urlRewriteResource->method('findConflicts')->willReturn([]);
        $this->urlRewriteResource->method('replaceProductRewrites')->willReturnCallback(
            function (array $entityIds, array $storeIds, array $rows): void {
                $this->replaced = ['entityIds' => $entityIds, 'storeIds' => $storeIds, 'rows' => $rows];
            }
        );
        $this->urlRewriteResource->method('deleteAutogenerated')->willReturnCallback(
            function (array $entityIds, array $storeIds): void {
                $this->deleted = ['entityIds' => $entityIds, 'storeIds' => $storeIds];
            }
        );

        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValues')->willReturn([]);
        $this->eavValue->method('getValuesForStores')->willReturn([]);

        $this->attributeMetadataCache = $this->createMock(AttributeMetadataCache::class);

        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1]);

        $this->config = $this->createMock(Config::class);
        $this->config->method('getUrlRewriteConflictStrategy')->willReturn(Config::URL_CONFLICT_APPEND);

        $this->categoryLink = $this->createMock(CategoryLink::class);
        $this->categoryPathRewriteBuilder = $this->createMock(CategoryPathRewriteBuilder::class);

        $this->productEntity = $this->createMock(ProductEntity::class);

        $this->rebuildProcessor();
    }

    /**
     * Rebuilds the processor from the current collaborators, so a test can swap
     * one out first — a mock's stubs cannot be replaced once set, and the
     * per-store tests need a different store list or EAV reader than setUp's.
     */
    private function rebuildProcessor(): void
    {
        $this->processor = new UrlRewriteProcessor(
            $this->urlRewriteResource,
            $this->eavValue,
            $this->attributeMetadataCache,
            $this->storeWebsiteMap,
            $this->config,
            $this->categoryLink,
            $this->categoryPathRewriteBuilder,
            $this->productEntity
        );
    }

    public function testSameBatchDuplicateUrlKeyIsDisambiguatedInsteadOfCollapsing(): void
    {
        $context = $this->createContext(['SKU-A' => 8454, 'SKU-B' => 8816], urlKey: 'shared-key');

        $this->processor->process($context);

        self::assertNotNull($this->replaced);
        $pathsByEntity = [];
        foreach ($this->replaced['rows'] as $row) {
            $pathsByEntity[$row['entity_id']] = $row['request_path'];
        }

        self::assertSame('shared-key.html', $pathsByEntity[8454]);
        self::assertSame('shared-key-8816.html', $pathsByEntity[8816]);
        self::assertSame([], $context->getMessages('SKU-A'));
        self::assertStringContainsString('is taken in store 1', $context->getMessages('SKU-B')[0]);
    }

    /**
     * The point of the whole phase: a store view that has its own slug resolves
     * on it, while its neighbours keep the default one.
     */
    public function testEachStoreGetsARequestPathBuiltFromItsOwnUrlKey(): void
    {
        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1, 2]);
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(false);
        $this->rebuildProcessor();

        $context = $this->createContext(['SKU-A' => 42], urlKey: 'white-shirt');
        $context->set(EavValueProcessor::CONTEXT_URL_KEYS, [
            'SKU-A' => [0 => 'white-shirt', 2 => 'weisses-hemd'],
        ]);

        $this->processor->process($context);

        self::assertNotNull($this->replaced);
        $pathsByStore = [];
        foreach ($this->replaced['rows'] as $row) {
            $pathsByStore[$row['store_id']] = $row['request_path'];
        }
        self::assertSame(['white-shirt.html', 'weisses-hemd.html'], [$pathsByStore[1], $pathsByStore[2]]);
    }

    /**
     * A store override this batch did not write is still the slug that store
     * resolves on. Regenerating its rewrite from the default key would discard
     * the override — including one an earlier run of this module wrote, making
     * a replay flip the storefront URL back and forth.
     */
    public function testAStoredStoreOverrideSurvivesADefaultScopeOnlyPayload(): void
    {
        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1, 2]);
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(false);
        $this->attributeMetadataCache->method('get')->willReturnCallback(
            static fn (string $code): ?array => $code === 'url_key'
                ? ['attribute_id' => 97, 'attribute_code' => 'url_key', 'backend_type' => 'varchar']
                : null
        );
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValues')->willReturn([]);
        // Every scope in one read: only store 2 carries an override, store 1
        // falls back to the default key.
        $this->eavValue->expects(self::once())->method('getValuesForStores')
            ->willReturn([77 => [97 => [2 => 'weisses-hemd']]]);
        $this->rebuildProcessor();

        $context = $this->createContext(['SKU-A' => 42], urlKey: 'white-shirt', linkIds: ['SKU-A' => 77]);

        $this->processor->process($context);

        self::assertNotNull($this->replaced);
        $pathsByStore = [];
        foreach ($this->replaced['rows'] as $row) {
            $pathsByStore[$row['store_id']] = $row['request_path'];
        }
        self::assertSame(['white-shirt.html', 'weisses-hemd.html'], [$pathsByStore[1], $pathsByStore[2]]);
    }

    public function testTheBatchesOwnScopedKeyWinsOverTheStoredOne(): void
    {
        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([2]);
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(false);
        $this->attributeMetadataCache->method('get')->willReturnCallback(
            static fn (string $code): ?array => $code === 'url_key'
                ? ['attribute_id' => 97, 'attribute_code' => 'url_key', 'backend_type' => 'varchar']
                : null
        );
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValues')->willReturn([]);
        $this->eavValue->method('getValuesForStores')->willReturn([77 => [97 => [2 => 'stale-slug']]]);
        $this->rebuildProcessor();

        $context = $this->createContext(['SKU-A' => 42], urlKey: 'white-shirt', linkIds: ['SKU-A' => 77]);
        $context->set(EavValueProcessor::CONTEXT_URL_KEYS, [
            'SKU-A' => [0 => 'white-shirt', 2 => 'fresh-slug'],
        ]);

        $this->processor->process($context);

        self::assertSame('fresh-slug.html', $this->replaced['rows'][0]['request_path']);
    }

    public function testCategoryPathRewritesUseTheStoresOwnUrlKey(): void
    {
        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1, 2]);
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(true);
        $this->categoryLink->method('getAssignments')->willReturn([42 => [5]]);
        $seenKeys = [];
        $this->categoryPathRewriteBuilder->method('build')->willReturnCallback(
            function (array $assignments, array $urlKeyByEntity, int $storeId) use (&$seenKeys): array {
                $seenKeys[$storeId] = $urlKeyByEntity[42] ?? null;

                return [];
            }
        );
        $this->rebuildProcessor();

        $context = $this->createContext(['SKU-A' => 42], urlKey: 'white-shirt');
        $context->set(EavValueProcessor::CONTEXT_URL_KEYS, [
            'SKU-A' => [0 => 'white-shirt', 2 => 'weisses-hemd'],
        ]);

        $this->processor->process($context);

        self::assertSame([1 => 'white-shirt', 2 => 'weisses-hemd'], $seenKeys);
    }

    public function testCanonicalOnlyWhenCategoryRewritesDisabled(): void
    {
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(false);

        $this->processor->process($this->createContext(['SKU-A' => 42], urlKey: 'white-shirt'));

        self::assertNotNull($this->replaced);
        self::assertCount(1, $this->replaced['rows']);
        self::assertSame('white-shirt.html', $this->replaced['rows'][0]['request_path']);
        self::assertNull($this->replaced['rows'][0]['metadata']);
    }

    public function testCategoryPathRewritesGeneratedWhenEnabled(): void
    {
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(true);
        $this->categoryLink->method('getAssignments')->willReturn([42 => [5]]);
        $this->categoryPathRewriteBuilder->method('build')->willReturn([
            42 => [[
                'request_path' => 'men/tops/white-shirt.html',
                'target_path' => 'catalog/product/view/id/42/category/5',
                'category_id' => 5,
            ]],
        ]);
        $relations = null;
        $this->urlRewriteResource->method('saveProductCategoryRelations')->willReturnCallback(
            function (array $entityIds, array $storeIds) use (&$relations): void {
                $relations = ['entityIds' => $entityIds, 'storeIds' => $storeIds];
            }
        );

        $this->processor->process($this->createContext(['SKU-A' => 42], urlKey: 'white-shirt'));

        self::assertNotNull($this->replaced);
        $byPath = [];
        foreach ($this->replaced['rows'] as $row) {
            $byPath[$row['request_path']] = $row;
        }
        self::assertArrayHasKey('white-shirt.html', $byPath);
        self::assertNull($byPath['white-shirt.html']['metadata']);
        self::assertArrayHasKey('men/tops/white-shirt.html', $byPath);
        self::assertSame(
            'catalog/product/view/id/42/category/5',
            $byPath['men/tops/white-shirt.html']['target_path']
        );
        self::assertSame('{"category_id":"5"}', $byPath['men/tops/white-shirt.html']['metadata']);
        self::assertSame(['entityIds' => [42], 'storeIds' => [1]], $relations);
    }

    public function testNotVisibleProductProducesNoRewritesAndIsDeleted(): void
    {
        $this->attributeMetadataCache->method('get')->willReturnCallback(
            static fn (string $code): ?array => $code === 'visibility'
                ? ['attribute_id' => 77, 'attribute_code' => 'visibility', 'backend_type' => 'int',
                   'frontend_input' => 'select', 'is_global' => 1, 'is_required' => 0]
                : null
        );
        // link id 99 has visibility = 1 (Not Visible) at store 0.
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValues')->willReturnCallback(
            static fn (string $type, int $attrId, array $linkIds, int $storeId = 0): array =>
                $type === 'int' && $attrId === 77 && $storeId === 0 ? [99 => 1] : []
        );
        $this->rebuildProcessor();

        $context = $this->createContext(['SKU-A' => 42], urlKey: 'white-shirt', linkIds: ['SKU-A' => 99]);
        $this->processor->process($context);

        self::assertNull($this->replaced, 'A not-visible product must produce no rewrites.');
        self::assertSame(['entityIds' => [42], 'storeIds' => [1]], $this->deleted);
    }

    public function testUrlKeyChangeProducesRedirectWhenHistoryEnabled(): void
    {
        $this->urlRewriteResource->method('isSaveRewritesHistory')->willReturn(true);
        $this->urlRewriteResource->method('getExistingAutogenerated')->willReturn([
            ['entity_id' => 42, 'store_id' => 1, 'request_path' => 'white-shirt.html',
             'target_path' => 'catalog/product/view/id/42', 'metadata' => null],
        ]);

        $this->processor->process($this->createContext(['SKU-A' => 42], urlKey: 'blue-shirt'));

        self::assertNotNull($this->replaced);
        $redirects = array_values(array_filter(
            $this->replaced['rows'],
            static fn (array $row): bool => $row['redirect_type'] === 301
        ));
        self::assertCount(1, $redirects);
        self::assertSame('white-shirt.html', $redirects[0]['request_path']);
        self::assertSame('blue-shirt.html', $redirects[0]['target_path']);
        self::assertSame(0, $redirects[0]['is_autogenerated']);
    }

    public function testNoRedirectWhenOldPathReclaimedByAnotherProductInBatch(): void
    {
        $this->urlRewriteResource->method('isSaveRewritesHistory')->willReturn(true);
        // Product 42's stored canonical was 'white-shirt.html' (its url_key changed).
        $this->urlRewriteResource->method('getExistingAutogenerated')->willReturn([
            ['entity_id' => 42, 'store_id' => 1, 'request_path' => 'white-shirt.html',
             'target_path' => 'catalog/product/view/id/42', 'metadata' => null],
        ]);

        // 42 now resolves to blue-shirt; 99 adopts the freed white-shirt url_key.
        $context = $this->createContextPerSku(['SKU-A' => [42, 'blue-shirt'], 'SKU-B' => [99, 'white-shirt']]);
        $this->processor->process($context);

        self::assertNotNull($this->replaced);
        $redirects = array_filter(
            $this->replaced['rows'],
            static fn (array $row): bool => $row['redirect_type'] === 301
        );
        self::assertCount(0, $redirects, 'No 301 may shadow a path re-claimed as a live rewrite this batch.');

        $pathByEntity = [];
        foreach ($this->replaced['rows'] as $row) {
            $pathByEntity[$row['entity_id']] = $row['request_path'];
        }
        self::assertSame('white-shirt.html', $pathByEntity[99]);
    }

    /**
     * @param array<string, array{0: int, 1: string}> $rows sku => [entity_id, url_key]
     */
    private function createContextPerSku(array $rows): BatchContext
    {
        $products = [];
        $urlKeys = [];
        $websiteIds = [];
        foreach ($rows as $sku => [$entityId, $urlKey]) {
            $products[] = (new Product())->setSku((string)$sku);
            $urlKeys[$sku] = [0 => $urlKey];
            $websiteIds[$sku] = [1];
        }

        $context = new BatchContext($products, 0);
        foreach ($rows as $sku => [$entityId, $urlKey]) {
            $context->setEntityId($sku, $entityId);
        }
        $context->set(EavValueProcessor::CONTEXT_URL_KEYS, $urlKeys);
        $context->set(WebsiteProcessor::CONTEXT_WEBSITE_IDS, $websiteIds);

        return $context;
    }

    /**
     * @param array<string, int> $entityIdsBySku
     * @param array<string, int> $linkIds
     */
    private function createContext(array $entityIdsBySku, string $urlKey, array $linkIds = []): BatchContext
    {
        $products = [];
        $urlKeys = [];
        $websiteIds = [];
        foreach ($entityIdsBySku as $sku => $entityId) {
            $products[] = (new Product())->setSku((string)$sku);
            $urlKeys[$sku] = [0 => $urlKey];
            $websiteIds[$sku] = [1];
        }

        $context = new BatchContext($products, 0);
        foreach ($entityIdsBySku as $sku => $entityId) {
            $context->setEntityId($sku, $entityId);
        }
        $context->set(EavValueProcessor::CONTEXT_URL_KEYS, $urlKeys);
        $context->set(WebsiteProcessor::CONTEXT_WEBSITE_IDS, $websiteIds);
        if ($linkIds) {
            $context->set(EntityProcessor::CONTEXT_LINK_IDS, $linkIds);
        }

        return $context;
    }

    // ---------------------------------------------------------------------
    // requiredLocks(): the probe runs BEFORE the transaction, so it reads the
    // payload and the database directly rather than the context data bag.
    // ---------------------------------------------------------------------

    /**
     * The property the whole probe exists for. A feed re-sending slugs it already
     * sent claims only paths it already owns, so re-writing them is idempotent
     * and there is nothing to serialize. If this ever starts taking the lock,
     * every batch of every steady-state push serializes against every other
     * import — which is what the per-batch probe design was built to avoid.
     */
    public function testAPayloadWhoseSlugsAllMatchTheStoredOnesTakesNoLock(): void
    {
        $this->stubUrlKeyMeta();
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValuesForStores')->willReturn([77 => [97 => [0 => 'white-shirt']]]);
        $this->rebuildProcessor();

        $context = $this->probeContext(['SKU-A' => 'white-shirt']);

        self::assertSame([], $this->processor->requiredLocks($context));
    }

    public function testAChangedSlugTakesTheRewriteLock(): void
    {
        $this->stubUrlKeyMeta();
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValuesForStores')->willReturn([77 => [97 => [0 => 'white-shirt']]]);
        $this->rebuildProcessor();

        $context = $this->probeContext(['SKU-A' => 'cream-shirt']);

        self::assertSame([ImportLocks::URL_REWRITE], $this->processor->requiredLocks($context));
    }

    /**
     * A new product always claims a path — EavValueProcessor derives a url_key
     * from the name when the payload omits one — so the answer is known without
     * comparing anything. The EAV read must not happen: on a first-time import
     * every batch is new, and that is the batch where an extra query costs most.
     */
    public function testANewSkuShortCircuitsWithoutReadingStoredKeys(): void
    {
        $this->productEntity->method('getExistingBySkus')->willReturn([]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->expects(self::never())->method('getValuesForStores');
        $this->rebuildProcessor();

        $context = $this->probeContext(['SKU-A' => 'white-shirt']);

        self::assertSame([ImportLocks::URL_REWRITE], $this->processor->requiredLocks($context));
    }

    /**
     * A price or stock refresh names no slug at all, so it can claim nothing.
     * One indexed read, no lock — the module's documented fast path.
     */
    public function testAPayloadWithNoUrlKeyAnywhereMakesNoEavReadAndTakesNoLock(): void
    {
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->expects(self::never())->method('getValuesForStores');
        $this->rebuildProcessor();

        $context = new BatchContext([(new Product())->setSku('SKU-A')], 0);

        self::assertSame([], $this->processor->requiredLocks($context));
    }

    /**
     * url_key is store-scoped, so a request naming store 2 writes the store-2
     * row — not store 0. Comparing against store 0 would call this a change.
     */
    public function testARequestScopedKeyIsComparedAgainstThatStoresOwnRow(): void
    {
        $this->stubUrlKeyMeta();
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValuesForStores')->willReturn([
            77 => [97 => [0 => 'white-shirt', 2 => 'weisses-hemd']],
        ]);
        $this->rebuildProcessor();

        $context = new BatchContext([(new Product())->setSku('SKU-A')->setUrlKey('weisses-hemd')], 2);

        self::assertSame([], $this->processor->requiredLocks($context));
    }

    /**
     * The other direction of the same rule: matching the store-0 row is NOT a
     * match when the request addresses store 2 and store 2 has its own value.
     */
    public function testARequestScopedKeyMatchingOnlyTheDefaultRowIsAChange(): void
    {
        $this->stubUrlKeyMeta();
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValuesForStores')->willReturn([
            77 => [97 => [0 => 'white-shirt', 2 => 'weisses-hemd']],
        ]);
        $this->rebuildProcessor();

        $context = new BatchContext([(new Product())->setSku('SKU-A')->setUrlKey('white-shirt')], 2);

        self::assertSame([ImportLocks::URL_REWRITE], $this->processor->requiredLocks($context));
    }

    /**
     * A store with no override of its own resolves on the default value, so that
     * is what a block's key is compared against — mirroring urlKeyFor(). Without
     * this the probe would report a change for a block that changes nothing.
     */
    public function testABlockKeyFallsBackToTheDefaultRowWhenTheStoreHasNoOverride(): void
    {
        $this->stubUrlKeyMeta();
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValuesForStores')->willReturn([77 => [97 => [0 => 'white-shirt']]]);
        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1]);
        $this->storeWebsiteMap->method('findScopeStoreId')->willReturn(2);
        $this->rebuildProcessor();

        $product = (new Product())->setSku('SKU-A');
        $product->setStoreValues([(new ProductStoreValues())->setStoreId(2)->setUrlKey('white-shirt')]);
        $context = new BatchContext([$product], 0);

        self::assertSame([], $this->processor->requiredLocks($context));
    }

    /**
     * The contention case for localized feeds: per-store slugs are re-sent on
     * every push, and the store-scoped comparison is exact precisely so those
     * batches stay lock-free. A conservative "carries a store url_key" predicate
     * would lock every one of them.
     */
    public function testAChangedStoreScopedKeyTakesTheLock(): void
    {
        $this->stubUrlKeyMeta();
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValuesForStores')->willReturn([
            77 => [97 => [0 => 'white-shirt', 2 => 'weisses-hemd']],
        ]);
        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1]);
        $this->storeWebsiteMap->method('findScopeStoreId')->willReturn(2);
        $this->rebuildProcessor();

        $product = (new Product())->setSku('SKU-A');
        $product->setStoreValues([(new ProductStoreValues())->setStoreId(2)->setUrlKey('creme-hemd')]);
        $context = new BatchContext([$product], 0);

        self::assertSame([ImportLocks::URL_REWRITE], $this->processor->requiredLocks($context));
    }

    /**
     * EavValueProcessor refuses both, so neither writes a value and neither can
     * claim a path.
     */
    public function testBlocksThatWriteNothingAreNotClaims(): void
    {
        $this->stubUrlKeyMeta();
        $this->productEntity->method('getExistingBySkus')
            ->willReturn(['SKU-A' => ['entity_id' => 42, 'link_id' => 77]]);
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->expects(self::never())->method('getValuesForStores');
        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1]);
        // An unknown store view resolves to null; the default scope resolves to 0.
        $this->storeWebsiteMap->method('findScopeStoreId')->willReturnOnConsecutiveCalls(null, 0);
        $this->rebuildProcessor();

        $product = (new Product())->setSku('SKU-A');
        $product->setStoreValues([
            (new ProductStoreValues())->setStoreViewCode('nope')->setUrlKey('whatever'),
            (new ProductStoreValues())->setStoreId(0)->setUrlKey('whatever'),
        ]);
        $context = new BatchContext([$product], 0);

        self::assertSame([], $this->processor->requiredLocks($context));
    }

    public function testAnEmptyBatchAsksTheDatabaseNothing(): void
    {
        $this->productEntity->expects(self::never())->method('getExistingBySkus');
        $this->rebuildProcessor();

        self::assertSame([], $this->processor->requiredLocks(new BatchContext([], 0)));
    }

    /**
     * This step deliberately has no holdsLock() degradation, unlike every other
     * lock-aware one. Skipping the write would leave the product with NO url at
     * all, because replaceProductRewrites() deletes our own rows before
     * inserting — strictly worse than a write that merely displaced someone
     * else's. Pinned so the "missing" check is not added later.
     */
    public function testRewritesAreStillWrittenWhenTheBatchHoldsNoLock(): void
    {
        $context = $this->createContext(['SKU-A' => 42], urlKey: 'white-shirt');
        $context->setHeldLocks([]);

        $this->processor->process($context);

        self::assertNotNull($this->replaced);
        self::assertNotSame([], $this->replaced['rows']);
    }

    /**
     * @param array<string, string> $urlKeyBySku
     */
    private function probeContext(array $urlKeyBySku, int $storeId = 0): BatchContext
    {
        $products = [];
        foreach ($urlKeyBySku as $sku => $urlKey) {
            $products[] = (new Product())->setSku((string)$sku)->setUrlKey($urlKey);
        }

        return new BatchContext($products, $storeId);
    }

    private function stubUrlKeyMeta(): void
    {
        $this->attributeMetadataCache = $this->createMock(AttributeMetadataCache::class);
        $this->attributeMetadataCache->method('get')->willReturnCallback(
            static fn (string $code): ?array => $code === 'url_key'
                ? ['attribute_id' => 97, 'attribute_code' => 'url_key', 'backend_type' => 'varchar']
                : null
        );
    }
}
