<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Model\Processor;

use ReadyData\Import\Api\Data\ProductInterface;
use ReadyData\Import\Model\BatchContext;
use ReadyData\Import\Model\Cache\AttributeMetadataCache;
use ReadyData\Import\Model\Cache\StoreWebsiteMap;
use ReadyData\Import\Model\Config;
use ReadyData\Import\Model\ImportLocks;
use ReadyData\Import\Model\Processor\UrlRewrite\CategoryPathRewriteBuilder;
use ReadyData\Import\Model\ResourceModel\CategoryLink;
use ReadyData\Import\Model\ResourceModel\EavValue;
use ReadyData\Import\Model\ResourceModel\ProductEntity;
use ReadyData\Import\Model\ResourceModel\UrlRewrite;

/**
 * Regenerates product URL rewrites for every store of the product's websites,
 * mirroring the native catalog-url-rewrite output:
 *  - the canonical (direct) product rewrite;
 *  - category-path rewrites incl. anchor-ancestor rollup, when the store has
 *    catalog/seo/generate_category_product_rewrites enabled;
 *  - 301 redirects from changed request paths, when the store has
 *    catalog/seo/save_rewrites_history enabled;
 *  - visibility-aware: not-visible products get no rewrites and their existing
 *    autogenerated rewrites are removed.
 *
 * Runs after CategoryLinkProcessor (sort order 750 > 700) so the final
 * product↔category assignments are readable.
 */
class UrlRewriteProcessor implements ProcessorInterface, LockAwareInterface
{
    private const VISIBILITY_NOT_VISIBLE = 1;
    private const REDIRECT_PERMANENT = 301;
    private const CANONICAL_KEY = 'c';

    /**
     * How many `<slug>-<entity_id>[-n]` variants the append strategy will try
     * before giving up and skipping the rewrite. See
     * {@see firstFreeAppendage()}.
     */
    private const MAX_APPEND_ATTEMPTS = 5;

    public function __construct(
        private readonly UrlRewrite $urlRewriteResource,
        private readonly EavValue $eavValue,
        private readonly AttributeMetadataCache $attributeMetadataCache,
        private readonly StoreWebsiteMap $storeWebsiteMap,
        private readonly Config $config,
        private readonly CategoryLink $categoryLink,
        private readonly CategoryPathRewriteBuilder $categoryPathRewriteBuilder,
        private readonly ProductEntity $productEntity
    ) {
    }

    /**
     * The rewrite lock, and only when this batch will claim a request path it
     * does not already own.
     *
     * The exact question is not answerable here: entity IDs for new products,
     * CONTEXT_WEBSITE_IDS and CONTEXT_LINK_IDS are all published inside the
     * transaction, so the candidate paths {@see process()} builds do not exist
     * yet. This is therefore a sound over-approximation on two signals:
     *
     * 1. **any new SKU** — a new product always claims a path, because
     *    EavValueProcessor generates a url_key from the name when the payload
     *    omits one. A short-circuit, not a computation;
     * 2. **a declared url_key that differs from the stored one**, in any scope.
     *    An existing product whose slug does not move claims only paths it
     *    already owns, and re-writing those is idempotent.
     *
     * So the fast paths stay lock-free: a price or stock refresh declares no
     * url_key at all and makes one indexed read; a feed re-sending unchanged
     * slugs — including per-store ones — compares equal and takes nothing.
     *
     * Deliberately NO {@see BatchContext::holdsLock()} degradation in
     * {@see process()}, unlike every other lock-aware step, because:
     *
     * - what this guards is not an unkeyed create. The key exists, the damage is
     *   a bounded overwrite rather than an unrecoverable duplicate row, and the
     *   ownership columns make the losing outcome coherent and self-healing on
     *   the next import;
     * - refusing would be WORSE. `replaceProductRewrites()` deletes our own
     *   autogenerated rows before inserting, so skipping a candidate leaves the
     *   product with no URL at all, where writing it leaves a correct one that
     *   merely displaced someone else's;
     * - it would not close the window anyway. The exposure is findConflicts() →
     *   INSERT, and no extra read closes that — only the lock does.
     */
    public function requiredLocks(BatchContext $context): array
    {
        $products = $context->getValidProducts();
        if (!$products) {
            return [];
        }

        $existing = $this->productEntity->getExistingBySkus(array_keys($products));
        if (count($existing) !== count($products)) {
            return [ImportLocks::URL_REWRITE];
        }

        $declared = $this->declaredUrlKeys($context);
        if (!$declared) {
            return [];
        }

        return $this->movesASlug($declared, $existing) ? [ImportLocks::URL_REWRITE] : [];
    }

    /**
     * The url_keys this payload actually writes, and the store row each lands in.
     *
     * Mirrors EavValueProcessor's scope resolution rather than guessing at it:
     * `url_key` is store-scoped (`is_global = 0`), so the base pass lands at the
     * REQUEST's scope — NOT store 0 — and each store_values block lands at its
     * own. Comparing a request-scoped key against the store-0 row would report a
     * real change as unchanged, and a no-op as a change.
     *
     * Skipped, because EavValueProcessor writes nothing for them: an empty key
     * (which makes process() skip the product entirely), a block naming a store
     * view that does not resolve, and a block naming the default scope.
     *
     * @return array<string, array<int, string>> sku => store_id => url_key
     */
    private function declaredUrlKeys(BatchContext $context): array
    {
        $declared = [];
        foreach ($context->getValidProducts() as $sku => $product) {
            $urlKey = $product->getUrlKey();
            if ($urlKey !== null && $urlKey !== '') {
                $declared[(string)$sku][$context->getStoreId()] = $urlKey;
            }

            foreach ($product->getStoreValues() ?? [] as $block) {
                $blockKey = $block->getUrlKey();
                if ($blockKey === null || $blockKey === '') {
                    continue;
                }
                $storeId = $this->storeWebsiteMap->findScopeStoreId(
                    $block->getStoreId(),
                    $block->getStoreViewCode()
                );
                if ($storeId !== null && $storeId !== 0) {
                    $declared[(string)$sku][$storeId] = $blockKey;
                }
            }
        }

        return $declared;
    }

    /**
     * Whether any declared url_key differs from what is stored for that scope.
     *
     * One indexed read covering EVERY scope, which is what lets the per-store
     * comparison be exact instead of conservative — a localized feed shipping
     * unchanged per-store slugs on every push must not take the lock.
     *
     * The fall-back mirrors {@see urlKeyFor()}: a store with no row of its own
     * resolves on the default-scope value, so that is what a block's key has to
     * be compared against. Comparison is untrimmed and byte-exact, because
     * EavValueProcessor's prepareValue() is a (string) passthrough for varchar
     * and the probe must agree with the write about what "unchanged" means.
     *
     * @param array<string, array<int, string>> $declared
     * @param array<string, array{link_id: int}> $existing keyed by SKU
     */
    private function movesASlug(array $declared, array $existing): bool
    {
        $meta = $this->attributeMetadataCache->get(ProductInterface::URL_KEY);
        if ($meta === null) {
            // No url_key attribute at all: nothing can be written, so nothing
            // can be claimed.
            return false;
        }

        $linkIdBySku = [];
        foreach (array_keys($declared) as $sku) {
            if (isset($existing[$sku]['link_id'])) {
                $linkIdBySku[$sku] = $existing[$sku]['link_id'];
            }
        }
        if (!$linkIdBySku) {
            return true;
        }

        $stored = $this->eavValue->getValuesForStores(
            $meta['backend_type'],
            [$meta['attribute_id']],
            array_values($linkIdBySku)
        );

        foreach ($declared as $sku => $byStore) {
            $byScope = $stored[$linkIdBySku[$sku] ?? 0][$meta['attribute_id']] ?? [];
            foreach ($byStore as $storeId => $urlKey) {
                $current = $byScope[$storeId] ?? $byScope[0] ?? '';
                if ($current !== $urlKey) {
                    return true;
                }
            }
        }

        return false;
    }

    public function process(BatchContext $context): void
    {
        $urlKeys = $this->resolveUrlKeys($context);
        $websiteIdsBySku = $context->get(WebsiteProcessor::CONTEXT_WEBSITE_IDS, []);
        $linkIds = $context->get(EntityProcessor::CONTEXT_LINK_IDS, []);
        $strategy = $this->config->getUrlRewriteConflictStrategy();

        // sku => [store ids] for products with a url_key and a resolved entity.
        // The DEFAULT-scope key is what decides whether a product has one at
        // all: a store override with nothing to override is not a slug.
        $storeIdsBySku = [];
        $skuByEntity = [];
        foreach (array_keys($context->getValidProducts()) as $sku) {
            $entityId = $context->getEntityId($sku);
            if (($urlKeys[$sku][0] ?? '') === '' || $entityId === null) {
                continue;
            }
            $storeIdsBySku[$sku] = $this->storeWebsiteMap->getStoreIdsForWebsites($websiteIdsBySku[$sku] ?? []);
            $skuByEntity[$entityId] = (string)$sku;
        }
        if (!$storeIdsBySku) {
            return;
        }

        $allStoreIds = array_values(array_unique(array_merge(...array_values($storeIdsBySku))));
        // Only knowable once the stores are: a store override this batch did
        // not write is still the slug that store's rewrite must be built from.
        $urlKeys = $this->backfillScopedUrlKeys($context, $urlKeys, $allStoreIds);
        $visibility = $this->loadVisibility(array_values($linkIds), $allStoreIds);

        // Canonical candidates + per-store visible-entity sets + not-visible sets.
        $canonical = [];
        $visibleEntitiesByStore = [];
        $notVisibleByStore = [];
        foreach ($storeIdsBySku as $sku => $storeIds) {
            $entityId = $context->getEntityId((string)$sku);
            $linkId = $linkIds[$sku] ?? null;
            foreach ($storeIds as $storeId) {
                if ($linkId !== null
                    && (int)($visibility[$storeId][$linkId] ?? 0) === self::VISIBILITY_NOT_VISIBLE
                ) {
                    $notVisibleByStore[$storeId][$entityId] = true;
                    continue;
                }
                $visibleEntitiesByStore[$storeId][$entityId] = true;
                $canonical[] = [
                    'sku' => (string)$sku,
                    'entity_id' => $entityId,
                    'store_id' => $storeId,
                    'request_path' => self::urlKeyFor($urlKeys, (string)$sku, $storeId)
                        . $this->urlRewriteResource->getProductUrlSuffix($storeId),
                    'target_path' => 'catalog/product/view/id/' . $entityId,
                    'metadata' => null,
                    'category_key' => self::CANONICAL_KEY,
                ];
            }
        }

        $category = $this->buildCategoryCandidates($context, $skuByEntity, $urlKeys, $visibleEntitiesByStore);

        // Resolve conflicts (canonical first so it keeps the clean path), build rows.
        $candidates = array_merge($canonical, $category);
        $allPaths = array_values(array_unique(array_map(
            static fn (array $c): string => $c['request_path'],
            $candidates
        )));
        $conflicts = $allPaths
            ? $this->urlRewriteResource->findConflicts($allPaths, $context->getValidEntityIds())
            : [];

        // Every path whose database status is known, i.e. every path asked about.
        // Not per store: findConflicts() filters on `request_path IN (...)` across
        // all of them, so asking about a path answers it for every store.
        $known = array_fill_keys($allPaths, true);

        // The second conflict lookup. `append` is the only strategy that invents a
        // path, and an invented path is never in $allPaths — so without this, the
        // one path this step writes is the one it never checked, and the upsert's
        // REPLACE_UPDATE_COLUMNS would take over whatever holds it.
        //
        // Only the variants of candidates that will actually collide are probed,
        // which is nothing at all for the overwhelming majority of batches. The
        // alternative — folding every candidate's variants into the first lookup —
        // widens the IN list MAX_APPEND_ATTEMPTS-fold on every batch to serve the
        // rare one.
        if ($strategy === Config::URL_CONFLICT_APPEND) {
            $variants = array_values(array_diff(
                $this->probeAppendVariants($context, $candidates, $conflicts),
                $allPaths
            ));
            if ($variants) {
                $variantConflicts = $this->urlRewriteResource->findConflicts(
                    $variants,
                    $context->getValidEntityIds()
                );
                foreach ($variantConflicts as $storeId => $paths) {
                    $conflicts[$storeId] = ($conflicts[$storeId] ?? []) + $paths;
                }
                $known += array_fill_keys($variants, true);
            }
        }

        $rows = [];
        $touchedEntityIds = [];
        $touchedStoreIds = [];
        $claimed = [];
        $finalByKey = [];
        $hasCategoryRows = false;
        foreach ($candidates as $candidate) {
            $sku = $candidate['sku'];
            // A SKU failed during conflict resolution (error strategy) must not
            // still receive its remaining (e.g. category-path) rewrites.
            if ($context->isFailed($sku)) {
                continue;
            }
            $storeId = $candidate['store_id'];
            $requestPath = $candidate['request_path'];
            if (isset($conflicts[$storeId][$requestPath]) || isset($claimed[$storeId][$requestPath])) {
                $requestPath = $this->resolveConflict(
                    $context,
                    $sku,
                    $storeId,
                    $requestPath,
                    $strategy,
                    // Both halves of "already spoken for": what the database
                    // reported for this store, and what earlier candidates in
                    // this batch have claimed. The append strategy has to avoid
                    // both, or it hands back a path it never checked.
                    ($conflicts[$storeId] ?? []) + ($claimed[$storeId] ?? []),
                    $known
                );
                if ($requestPath === null) {
                    continue;
                }
            }
            $claimed[$storeId][$requestPath] = true;
            $rows[] = [
                'entity_type' => UrlRewrite::ENTITY_TYPE_PRODUCT,
                'entity_id' => $candidate['entity_id'],
                'request_path' => $requestPath,
                'target_path' => $candidate['target_path'],
                'redirect_type' => 0,
                'store_id' => $storeId,
                'is_autogenerated' => 1,
                'metadata' => $candidate['metadata'],
            ];
            $hasCategoryRows = $hasCategoryRows || $candidate['metadata'] !== null;
            $touchedEntityIds[$candidate['entity_id']] = true;
            $touchedStoreIds[$storeId] = true;
            $finalByKey[$candidate['entity_id']][$storeId][$candidate['category_key']] = $requestPath;
        }

        if ($rows) {
            $rows = array_merge(
                $rows,
                $this->buildRedirects(
                    array_keys($touchedEntityIds),
                    array_keys($touchedStoreIds),
                    $finalByKey,
                    $claimed
                )
            );
            $this->urlRewriteResource->replaceProductRewrites(
                array_keys($touchedEntityIds),
                array_keys($touchedStoreIds),
                $rows
            );
            if ($hasCategoryRows) {
                $this->urlRewriteResource->saveProductCategoryRelations(
                    array_keys($touchedEntityIds),
                    array_keys($touchedStoreIds)
                );
            }
        }

        // Drop rewrites of products that became not-visible (per store, precise).
        foreach ($notVisibleByStore as $storeId => $entitySet) {
            $this->urlRewriteResource->deleteAutogenerated(array_keys($entitySet), [$storeId]);
        }
    }

    /**
     * Category-path + anchor candidates per enabled store, for visible products
     * only. Uses the final assignments written by CategoryLinkProcessor.
     *
     * @param array<int, string> $skuByEntity
     * @param array<string, array<int, string>> $urlKeys sku => store_id => url_key
     * @param array<int, array<int, true>> $visibleEntitiesByStore store => entity set
     * @return array<int, array<string, mixed>> flat candidate list
     */
    private function buildCategoryCandidates(
        BatchContext $context,
        array $skuByEntity,
        array $urlKeys,
        array $visibleEntitiesByStore
    ): array {
        $enabledStores = array_filter(
            array_keys($visibleEntitiesByStore),
            fn (int $storeId): bool => $this->urlRewriteResource->isCategoryRewritesEnabled($storeId)
        );
        if (!$enabledStores) {
            return [];
        }

        $assignments = $this->categoryLink->getAssignments($context->getValidEntityIds());
        if (!$assignments) {
            return [];
        }

        $candidates = [];
        foreach ($enabledStores as $storeId) {
            $visibleAssignments = array_intersect_key($assignments, $visibleEntitiesByStore[$storeId]);
            if (!$visibleAssignments) {
                continue;
            }
            // Rebuilt per store: the slug a category path is suffixed with is
            // the one that store view resolves on, not the default one.
            $urlKeyByEntity = [];
            foreach ($skuByEntity as $entityId => $sku) {
                $urlKey = self::urlKeyFor($urlKeys, $sku, $storeId);
                if ($urlKey !== '') {
                    $urlKeyByEntity[$entityId] = $urlKey;
                }
            }
            $built = $this->categoryPathRewriteBuilder->build(
                $visibleAssignments,
                $urlKeyByEntity,
                $storeId,
                $this->urlRewriteResource->getProductUrlSuffix($storeId)
            );
            foreach ($built as $entityId => $entityCandidates) {
                foreach ($entityCandidates as $candidate) {
                    $candidates[] = [
                        'sku' => $skuByEntity[$entityId] ?? '',
                        'entity_id' => $entityId,
                        'store_id' => $storeId,
                        'request_path' => $candidate['request_path'],
                        'target_path' => $candidate['target_path'],
                        'metadata' => json_encode(['category_id' => (string)$candidate['category_id']]),
                        'category_key' => $candidate['category_id'],
                    ];
                }
            }
        }

        return $candidates;
    }

    /**
     * 301 rows for request paths that changed: for each existing autogenerated
     * rewrite whose category context still resolves to a (different) new path.
     *
     * @param int[] $entityIds
     * @param int[] $storeIds
     * @param array<int, array<int, array<int|string, string>>> $finalByKey
     *        entity_id => store_id => category_key => new request path
     * @param array<int, array<string, true>> $claimed store_id => set of request paths
     *        written this batch as live rewrites
     * @return array<int, array<string, mixed>>
     */
    private function buildRedirects(array $entityIds, array $storeIds, array $finalByKey, array $claimed): array
    {
        $historyStores = array_values(array_filter(
            $storeIds,
            fn (int $storeId): bool => $this->urlRewriteResource->isSaveRewritesHistory($storeId)
        ));
        if (!$historyStores) {
            return [];
        }

        $redirects = [];
        foreach ($this->urlRewriteResource->getExistingAutogenerated($entityIds, $historyStores) as $old) {
            $key = $this->categoryKeyFromMetadata($old['metadata']);
            $newPath = $finalByKey[$old['entity_id']][$old['store_id']][$key] ?? null;
            if ($newPath === null || $newPath === $old['request_path']) {
                continue;
            }
            // The old path was re-claimed as a live rewrite this batch (e.g.
            // another product adopted the freed url_key) — do not shadow it
            // with a 301, which would overwrite that product's rewrite.
            if (isset($claimed[$old['store_id']][$old['request_path']])) {
                continue;
            }
            $redirects[] = [
                'entity_type' => UrlRewrite::ENTITY_TYPE_PRODUCT,
                'entity_id' => $old['entity_id'],
                'request_path' => $old['request_path'],
                'target_path' => $newPath,
                'redirect_type' => self::REDIRECT_PERMANENT,
                'store_id' => $old['store_id'],
                'is_autogenerated' => 0,
                'metadata' => $old['metadata'],
            ];
        }

        return $redirects;
    }

    /**
     * @return int|string the category id, or CANONICAL_KEY for non-category rows
     */
    private function categoryKeyFromMetadata(?string $metadata): int|string
    {
        if ($metadata === null || $metadata === '') {
            return self::CANONICAL_KEY;
        }
        $decoded = json_decode($metadata, true);

        return is_array($decoded) && isset($decoded['category_id'])
            ? (int)$decoded['category_id']
            : self::CANONICAL_KEY;
    }

    /**
     * Visibility per store keyed by link id, with store-0 fallback.
     *
     * @param int[] $linkIds
     * @param int[] $storeIds
     * @return array<int, array<int, int>> store_id => [link_id => visibility]
     */
    private function loadVisibility(array $linkIds, array $storeIds): array
    {
        if (!$linkIds) {
            return [];
        }
        $meta = $this->attributeMetadataCache->get(ProductInterface::VISIBILITY);
        if ($meta === null) {
            return [];
        }
        $attributeId = $meta['attribute_id'];
        $backendType = $meta['backend_type'];
        $store0 = $this->eavValue->getValues($backendType, $attributeId, $linkIds, 0);

        $result = [];
        foreach ($storeIds as $storeId) {
            $storeValues = $storeId === 0
                ? $store0
                : $this->eavValue->getValues($backendType, $attributeId, $linkIds, $storeId);
            // Store-specific values override the store-0 defaults.
            $result[$storeId] = array_map('intval', $storeValues + $store0);
        }

        return $result;
    }

    /**
     * The slug a store view resolves this product on: its own override when it
     * has one, the default-scope key otherwise — exactly how Magento reads a
     * store-scoped EAV value.
     *
     * @param array<string, array<int, string>> $urlKeys sku => store_id => url_key
     */
    private static function urlKeyFor(array $urlKeys, string $sku, int $storeId): string
    {
        $scoped = $urlKeys[$sku][$storeId] ?? '';

        return $scoped !== '' ? $scoped : ($urlKeys[$sku][0] ?? '');
    }

    /**
     * Default-scope url_keys written this batch (from EavValueProcessor),
     * backfilled with the stored one for existing products the payload didn't
     * touch.
     *
     * @return array<string, array<int, string>> sku => store_id => url_key
     */
    private function resolveUrlKeys(BatchContext $context): array
    {
        $urlKeys = $context->get(EavValueProcessor::CONTEXT_URL_KEYS, []);
        $linkIds = $context->get(EntityProcessor::CONTEXT_LINK_IDS, []);

        $missingLinkIds = [];
        foreach ($context->getValidProducts() as $sku => $product) {
            if (!isset($urlKeys[$sku][0]) && isset($linkIds[$sku])) {
                $missingLinkIds[$linkIds[$sku]] = $sku;
            }
        }
        if ($missingLinkIds) {
            $meta = $this->attributeMetadataCache->get(ProductInterface::URL_KEY);
            if ($meta !== null) {
                $stored = $this->eavValue->getValues(
                    $meta['backend_type'],
                    $meta['attribute_id'],
                    array_keys($missingLinkIds)
                );
                foreach ($stored as $linkId => $urlKey) {
                    $urlKeys[$missingLinkIds[(int)$linkId]][0] = (string)$urlKey;
                }
            }
        }

        return $urlKeys;
    }

    /**
     * Fill in the STORE-scoped url_keys already in the database for the (sku,
     * store) pairs this batch did not write.
     *
     * Without it a payload that sets only the default key would regenerate
     * every store's rewrite from that key, silently discarding a store
     * override — including one this module wrote on an earlier run, which would
     * make a replay flip the storefront URL back and forth.
     *
     * @param array<string, array<int, string>> $urlKeys
     * @param int[] $storeIds
     * @return array<string, array<int, string>>
     */
    private function backfillScopedUrlKeys(BatchContext $context, array $urlKeys, array $storeIds): array
    {
        $linkIds = $context->get(EntityProcessor::CONTEXT_LINK_IDS, []);
        $meta = $this->attributeMetadataCache->get(ProductInterface::URL_KEY);
        $storeIds = array_values(array_filter($storeIds, static fn (int $storeId): bool => $storeId !== 0));
        if ($meta === null || !$storeIds || !$linkIds) {
            return $urlKeys;
        }

        $skuByLinkId = [];
        foreach ($context->getValidProducts() as $sku => $product) {
            if (isset($linkIds[$sku])) {
                $skuByLinkId[$linkIds[$sku]] = (string)$sku;
            }
        }
        if (!$skuByLinkId) {
            return $urlKeys;
        }

        // Every scope in one query — the same read MediaProcessor uses for its
        // store-scoped role attributes. Per-store reads would cost one query per
        // store view on a catalog where that number is the whole point.
        $wanted = array_fill_keys($storeIds, true);
        $stored = $this->eavValue->getValuesForStores(
            $meta['backend_type'],
            [$meta['attribute_id']],
            array_keys($skuByLinkId)
        );

        foreach ($stored as $linkId => $byAttribute) {
            $sku = $skuByLinkId[(int)$linkId] ?? null;
            if ($sku === null) {
                continue;
            }
            foreach ($byAttribute[$meta['attribute_id']] ?? [] as $storeId => $urlKey) {
                // Never over the batch's own write: that is the newer value.
                if (isset($wanted[$storeId]) && !isset($urlKeys[$sku][$storeId]) && (string)$urlKey !== '') {
                    $urlKeys[$sku][(int)$storeId] = (string)$urlKey;
                }
            }
        }

        return $urlKeys;
    }

    /**
     * @param array<string, true> $taken request paths already spoken for in this
     *        store — the union of what the database reported and what earlier
     *        candidates in this batch have claimed
     * @param array<string, true> $known every request path whose database status
     *        was actually asked about, store-independent
     * @return string|null the request path to use, or null to skip this rewrite
     */
    private function resolveConflict(
        BatchContext $context,
        string $sku,
        int $storeId,
        string $requestPath,
        string $strategy,
        array $taken,
        array $known
    ): ?string {
        switch ($strategy) {
            case Config::URL_CONFLICT_APPEND:
                $unique = $this->firstFreeAppendage($context, $sku, $storeId, $requestPath, $taken, $known);
                if ($unique === null) {
                    // Every candidate appendage was taken too. Skipping is the
                    // only honest outcome left: writing an unchecked path here
                    // would overwrite whatever holds it, and since the upsert
                    // now claims ownership (see UrlRewrite's
                    // REPLACE_UPDATE_COLUMNS) that overwrite takes the row
                    // outright rather than merely cross-wiring it — including a
                    // CMS page's or a category's.
                    $context->addMessage($sku, sprintf(
                        'URL "%s" is taken in store %d and no free variant was found; rewrite skipped.',
                        $requestPath,
                        $storeId
                    ));

                    return null;
                }

                $context->addMessage($sku, sprintf(
                    'URL "%s" is taken in store %d; used "%s" instead.',
                    $requestPath,
                    $storeId,
                    $unique
                ));

                return $unique;
            case Config::URL_CONFLICT_ERROR:
                $context->fail($sku, sprintf('URL "%s" is already taken in store %d.', $requestPath, $storeId));

                return null;
            default:
                $context->addMessage($sku, sprintf(
                    'URL "%s" is taken in store %d; rewrite skipped.',
                    $requestPath,
                    $storeId
                ));

                return null;
        }
    }

    /**
     * The first `<slug>-<entity_id>` variant of a taken path that is KNOWN to be
     * free, or null when the bounded search is exhausted.
     *
     * The entity ID alone used to be assumed unique and was returned unchecked. It
     * usually IS unique, but it need not be: a product literally named "shirt-42"
     * derives the same slug, and two candidates in one batch can both append to
     * the same base. A discriminator is then added, bounded rather than unbounded
     * because a caller that has collided this many times is sending data that
     * needs fixing at the source, not a longer slug.
     *
     * Both conditions are load-bearing. `!isset($taken[...])` rules out the paths
     * the database reported and the ones earlier candidates claimed;
     * `isset($known[...])` additionally requires that somebody actually ASKED
     * about the path. {@see probeAppendVariants()} makes that true for every
     * variant of a candidate whose collision is predictable, which is all of them
     * bar one chain: a candidate whose own request path is the variant an earlier
     * candidate resolved to collides on $claimed alone, and its own variants were
     * therefore never probed. Refusing there costs that product its rewrite until
     * its next import — the same benign, self-healing outcome as every other
     * residual in this area — where writing an unqueried path would take over
     * whatever holds it, possibly a CMS page's or a product outside this feed's,
     * neither of which heals.
     *
     * @param array<string, true> $taken
     * @param array<string, true> $known
     */
    private function firstFreeAppendage(
        BatchContext $context,
        string $sku,
        int $storeId,
        string $requestPath,
        array $taken,
        array $known
    ): ?string {
        foreach ($this->appendVariants($context, $sku, $storeId, $requestPath) as $variant) {
            if (!isset($taken[$variant]) && isset($known[$variant])) {
                return $variant;
            }
        }

        return null;
    }

    /**
     * The variants firstFreeAppendage() will consider, in the order it considers
     * them. Its own generation logic, so the probe below and the resolver above
     * cannot drift — a second implementation of this sequence would silently
     * defeat the $known check by asking about paths that are never returned.
     *
     * @return string[]
     */
    private function appendVariants(
        BatchContext $context,
        string $sku,
        int $storeId,
        string $requestPath
    ): array {
        $suffix = $this->urlRewriteResource->getProductUrlSuffix($storeId);
        $base = $suffix !== '' && str_ends_with($requestPath, $suffix)
            ? substr($requestPath, 0, -strlen($suffix))
            : $requestPath;
        $base .= '-' . $context->getEntityId($sku);

        $variants = [];
        for ($attempt = 1; $attempt <= self::MAX_APPEND_ATTEMPTS; $attempt++) {
            $variants[] = ($attempt === 1 ? $base : $base . '-' . $attempt) . $suffix;
        }

        return $variants;
    }

    /**
     * Every appended path the write loop below could reach, for the second
     * findConflicts() lookup.
     *
     * A candidate needs a variant exactly when its request path is already spoken
     * for: reported by the first lookup for its store, or used by an earlier
     * candidate for that same store. Both are decidable here without replaying the
     * loop — which matters, because the loop reports per-SKU messages and fails
     * SKUs, and a dry run of it would do so twice.
     *
     * Deliberately not filtered by $context->isFailed(): only the `error` strategy
     * fails a SKU during resolution and this runs for `append` alone, so nothing is
     * failed yet. Probing a path that turns out not to be needed costs one entry in
     * an IN list.
     *
     * @param array<int, array<string, mixed>> $candidates
     * @param array<int, array<string, true>> $conflicts store_id => taken paths
     * @return string[] distinct paths
     */
    private function probeAppendVariants(BatchContext $context, array $candidates, array $conflicts): array
    {
        $seen = [];
        $variants = [];
        foreach ($candidates as $candidate) {
            $storeId = $candidate['store_id'];
            $requestPath = $candidate['request_path'];
            $collides = isset($conflicts[$storeId][$requestPath]) || isset($seen[$storeId][$requestPath]);
            $seen[$storeId][$requestPath] = true;
            if (!$collides) {
                continue;
            }
            foreach ($this->appendVariants($context, $candidate['sku'], $storeId, $requestPath) as $variant) {
                $variants[$variant] = true;
            }
        }

        return array_keys($variants);
    }

    public function isEnabled(): bool
    {
        return true;
    }

    public function getSortOrder(): int
    {
        return 750;
    }
}
